version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]